name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Setup python
    
    - name: Setup Node
      uses: actions/setup-node@v1
    
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        use-only-tar-bz2: true
    # - name: Set up Python 3.6.7
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: '3.6.7'
    #     architecture: 'x64' 
    - name: Install dependencies
      run: |
        # install conda
        # wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        # bash miniconda.sh -b -p $HOME/miniconda
        # export PATH="$HOME/miniconda/bin:$PATH"
        hash -r
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        # install yarn
        curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.1
        export PATH="$HOME/.yarn/bin:$PATH"
        # Useful for debugging any issues with conda
        conda info -a
    - name: install
      run: |
          yarn --cwd js
          # conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION coveralls
          # source activate test-environment
          # #now we are in an environment
          # conda install -c potassco clingo
          # pip install -r requirements.txt
          # pip install -e .
    - name: Test with pytest
      run: |
        yarn --cwd js build
        python setup.py test
        coveralls
